project:
  type: website

website:
  title: "Agustina Zuckerberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb
      - ./slides/slides.ipynb
      
format:
  html:
    theme: cosmo
    toc: true




